@ECHO OFF
:: This file is generated by buildenv tool -- see https://buildenv.readthedocs.io/
:: Please do not edit, changes will be lost

goto :start

:: Helper: print a command to stdout, then execute it
:run_cmd
echo [CMD] %*
%*
goto :eof

:: Check if uv is installed
:start
setlocal
uv --version > NUL 2> NUL
set _BUILDENV_RC=%ERRORLEVEL%
if %_BUILDENV_RC% NEQ 0 (
    echo|set /p="[ERROR] uv is not installed; see https://docs.astral.sh/uv/ for installation instructions" & echo.
    goto end
)

:: Export buildenv version
set BUILDENV_VERSION=2

:: Check for lock
set _opts=
if exist buildenv.lock (
    :: Locked requirements
    set _opts= --frozen
)

:: Delegate execution to buildenv command (through uv)
call :run_cmd uv run%_opts% %BUILDENV_UV_ARGS% buildenv %*
set _BUILDENV_RC=%ERRORLEVEL%
goto end

:end
exit /b %_BUILDENV_RC%
