#!/usr/bin/bash
# This file is generated by buildenv tool -- see https://buildenv.readthedocs.io/
# Please do not edit, changes will be lost

# Helper: print a command to stdout, then execute it
_run_cmd() {
    printf '[CMD] %s\n' "$*"
    "$@"
}

# Check if uv is installed
_run_cmd uv --version 2>/dev/null 1>&2
if test $? -ne 0; then
    echo "[ERROR] uv is not installed; see https://docs.astral.sh/uv/ for installation instructions"
    exit 1
fi

# Export buildenv version
export BUILDENV_VERSION=2

# Check for lock
_opts=""
if test -f buildenv.lock; then
    # Locked requirements
    _opts=" --frozen"
fi

# Delegate execution to buildenv command (through uv)
_run_cmd uv run${_opts} ${BUILDENV_UV_ARGS} buildenv "$@"
